/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-07-16 18:28:29 UTC)
 * on 2015-07-29 at 14:19:35 UTC 
 * Modify at your own risk.
 */

package com.appspot.futsalapp_1008.pdE2015.model;

/**
 * Model definition for InfoInvitoBean.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the pdE2015. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class InfoInvitoBean extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String emailDestinatario;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String emailMittente;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idGruppo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idInvito;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nomeGruppo;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmailDestinatario() {
    return emailDestinatario;
  }

  /**
   * @param emailDestinatario emailDestinatario or {@code null} for none
   */
  public InfoInvitoBean setEmailDestinatario(java.lang.String emailDestinatario) {
    this.emailDestinatario = emailDestinatario;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmailMittente() {
    return emailMittente;
  }

  /**
   * @param emailMittente emailMittente or {@code null} for none
   */
  public InfoInvitoBean setEmailMittente(java.lang.String emailMittente) {
    this.emailMittente = emailMittente;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdGruppo() {
    return idGruppo;
  }

  /**
   * @param idGruppo idGruppo or {@code null} for none
   */
  public InfoInvitoBean setIdGruppo(java.lang.Long idGruppo) {
    this.idGruppo = idGruppo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdInvito() {
    return idInvito;
  }

  /**
   * @param idInvito idInvito or {@code null} for none
   */
  public InfoInvitoBean setIdInvito(java.lang.Long idInvito) {
    this.idInvito = idInvito;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNomeGruppo() {
    return nomeGruppo;
  }

  /**
   * @param nomeGruppo nomeGruppo or {@code null} for none
   */
  public InfoInvitoBean setNomeGruppo(java.lang.String nomeGruppo) {
    this.nomeGruppo = nomeGruppo;
    return this;
  }

  @Override
  public InfoInvitoBean set(String fieldName, Object value) {
    return (InfoInvitoBean) super.set(fieldName, value);
  }

  @Override
  public InfoInvitoBean clone() {
    return (InfoInvitoBean) super.clone();
  }

}
