/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-07-16 18:28:29 UTC)
 * on 2015-07-29 at 14:19:35 UTC 
 * Modify at your own risk.
 */

package com.appspot.futsalapp_1008.pdE2015.model;

/**
 * Model definition for InfoGruppoBean.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the pdE2015. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class InfoGruppoBean extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean aperto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String citta;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nome;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAperto() {
    return aperto;
  }

  /**
   * @param aperto aperto or {@code null} for none
   */
  public InfoGruppoBean setAperto(java.lang.Boolean aperto) {
    this.aperto = aperto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCitta() {
    return citta;
  }

  /**
   * @param citta citta or {@code null} for none
   */
  public InfoGruppoBean setCitta(java.lang.String citta) {
    this.citta = citta;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public InfoGruppoBean setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNome() {
    return nome;
  }

  /**
   * @param nome nome or {@code null} for none
   */
  public InfoGruppoBean setNome(java.lang.String nome) {
    this.nome = nome;
    return this;
  }

  @Override
  public InfoGruppoBean set(String fieldName, Object value) {
    return (InfoGruppoBean) super.set(fieldName, value);
  }

  @Override
  public InfoGruppoBean clone() {
    return (InfoGruppoBean) super.clone();
  }

}
