/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-07-16 18:28:29 UTC)
 * on 2015-07-30 at 15:18:07 UTC 
 * Modify at your own risk.
 */

package com.appspot.futsalapp_1008.pdE2015.model;

/**
 * Model definition for InfoVotoUomoPartitaBean.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the pdE2015. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class InfoVotoUomoPartitaBean extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String commento;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long linkVotoPerPartita;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String votante;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String votato;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCommento() {
    return commento;
  }

  /**
   * @param commento commento or {@code null} for none
   */
  public InfoVotoUomoPartitaBean setCommento(java.lang.String commento) {
    this.commento = commento;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getLinkVotoPerPartita() {
    return linkVotoPerPartita;
  }

  /**
   * @param linkVotoPerPartita linkVotoPerPartita or {@code null} for none
   */
  public InfoVotoUomoPartitaBean setLinkVotoPerPartita(java.lang.Long linkVotoPerPartita) {
    this.linkVotoPerPartita = linkVotoPerPartita;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getVotante() {
    return votante;
  }

  /**
   * @param votante votante or {@code null} for none
   */
  public InfoVotoUomoPartitaBean setVotante(java.lang.String votante) {
    this.votante = votante;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getVotato() {
    return votato;
  }

  /**
   * @param votato votato or {@code null} for none
   */
  public InfoVotoUomoPartitaBean setVotato(java.lang.String votato) {
    this.votato = votato;
    return this;
  }

  @Override
  public InfoVotoUomoPartitaBean set(String fieldName, Object value) {
    return (InfoVotoUomoPartitaBean) super.set(fieldName, value);
  }

  @Override
  public InfoVotoUomoPartitaBean clone() {
    return (InfoVotoUomoPartitaBean) super.clone();
  }

}
