/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-07-16 18:28:29 UTC)
 * on 2015-07-26 at 12:07:35 UTC 
 * Modify at your own risk.
 */

package com.appspot.futsalapp_1008.pdE2015.model;

/**
 * Model definition for PayloadBean.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the pdE2015. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PayloadBean extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idGruppo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idPartita;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idSessione;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nuovoStato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profiloDaVisitare;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdGruppo() {
    return idGruppo;
  }

  /**
   * @param idGruppo idGruppo or {@code null} for none
   */
  public PayloadBean setIdGruppo(java.lang.Long idGruppo) {
    this.idGruppo = idGruppo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdPartita() {
    return idPartita;
  }

  /**
   * @param idPartita idPartita or {@code null} for none
   */
  public PayloadBean setIdPartita(java.lang.Long idPartita) {
    this.idPartita = idPartita;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdSessione() {
    return idSessione;
  }

  /**
   * @param idSessione idSessione or {@code null} for none
   */
  public PayloadBean setIdSessione(java.lang.Long idSessione) {
    this.idSessione = idSessione;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNuovoStato() {
    return nuovoStato;
  }

  /**
   * @param nuovoStato nuovoStato or {@code null} for none
   */
  public PayloadBean setNuovoStato(java.lang.String nuovoStato) {
    this.nuovoStato = nuovoStato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfiloDaVisitare() {
    return profiloDaVisitare;
  }

  /**
   * @param profiloDaVisitare profiloDaVisitare or {@code null} for none
   */
  public PayloadBean setProfiloDaVisitare(java.lang.String profiloDaVisitare) {
    this.profiloDaVisitare = profiloDaVisitare;
    return this;
  }

  @Override
  public PayloadBean set(String fieldName, Object value) {
    return (PayloadBean) super.set(fieldName, value);
  }

  @Override
  public PayloadBean clone() {
    return (PayloadBean) super.clone();
  }

}
